version: '3.8'

services:
  app:
    image: Beer:latest
    container_name: Beer_app
    environment:
      - NAVER_OAUTH_CLIENT_ID=${NAVER_OAUTH_CLIENT_ID}
      - NAVER_OAUTH_CLIENT_SECRET=${NAVER_OAUTH_CLIENT_SECRET}
      - KAKAO_OAUTH_CLIENT_ID=${KAKAO_OAUTH_CLIENT_ID}
      - KAKAO_OAUTH_CLIENT_SECRET=${KAKAO_OAUTH_CLIENT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    restart: unless-stopped
