name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Set up environment variables
        run: |
          echo "Setting up environment variables"
          # echo "NAVER_OAUTH_CLIENT_ID=${{ secrets.NAVER_OAUTH_CLIENT_ID }}" >> $GITHUB_ENV
          # echo "NAVER_OAUTH_CLIENT_SECRET=${{ secrets.NAVER_OAUTH_CLIENT_SECRET }}" >> $GITHUB_ENV
          # echo "KAKAO_OAUTH_CLIENT_ID=${{ secrets.KAKAO_OAUTH_CLIENT_ID }}" >> $GITHUB_ENV
          # echo "KAKAO_OAUTH_CLIENT_SECRET=${{ secrets.KAKAO_OAUTH_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          TAG=$(date +%s)
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/beer_back:${TAG}" .
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/beer_back:${{ env.TAG }}

      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TAG: ${{ env.TAG }}
        run: |
          echo "Deploying on EC2"
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd /beer
            docker pull ${DOCKERHUB_USERNAME}/beer_back:${TAG}
            docker stop beer || true
            docker rm beer || true
            docker run -d --name beer -p 8080:8080 ${DOCKERHUB_USERNAME}/beer_back:${TAG}
          EOF
